# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kbookmarks': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'

    # most PIM projects use @same to get other PIM deps,
    # but here we use @latest because kjots doesn't have a stable branch
    # or follow the release schedule of other PIM projects
    'pim/akonadi': '@latest-kf6'
    'pim/kmime': '@latest-kf6'
    'pim/akonadi-notes': '@latest-kf6'
    'pim/kpimtextedit': '@latest-kf6'
    'pim/kontactinterface': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'
    'frameworks/ktexttemplate': '@stable'
